### ISSUE TITLE
New suggestion for /orchestration/8.2.0/scripts-deep-dive.html

### ISSUE THREAD

**Issue by Kirizan** [QualiSystems/devguide_source#162]
Under the section: Logging in orchestration scripts, while it shows how to use the sandbox.logger, it never tells us where the logs will be placed.

**Comment by TomerAdmon** [comment]
**Thanks @Kirizan  👍** 
We will add some extra information about the subject.

For now, the CloudShell orchestration package - _cloudshell-orch-core_ is using _cloudshell-core_ for logging. The _cloudshell-core_ package allows us to create a standard logger(_qslogger_) for all cloudshell packages and shells so all logs will be stored under the same place.
For orchestration scripts, the _qslogger_ is creating a folder for every sandbox id and storing all the relevant logs under it. Every orchestration scripts that was executed on the sandbox will have it's on log file with the script name and unique identifier. For example:
--- 3b943acf-6eb6-4b55-93ad-6931f7b3d2e6
----------- Default Sandbox Setup 3.0_31_4B76F04C30D9734D823030A794699E03
----------- Default Sandbox Teardown 3.0_31_E44EEB519D102F4B95CC00FB2101C0FB

The sandbox logs folder can be found on the following paths:
**For Windows Execution Server:**
_C:\programdata\QualiSystems\logs_
**For Linux Execution Server:**
 _./usr/share/QualiSystems/logs_

Note that logs coming from within python packages can still be stored under the site-packages within the python virtual environment created for the python driver execution.

Thanks for the feedback, 
Tomer

**Comment by TomerAdmon** [comment]
@Shnitselon - can we close this one as we added this to the docs?

**Comment by Shnitselon** [comment]
@TomerAdmon yes
