### ISSUE TITLE
New suggestion for /reference/8.3.0/shellfoundry-intro.html

### ISSUE THREAD

**Issue by jporori** [QualiSystems/devguide_source#165]
Hi Our Documentation Team,

This is Dennis Chen from Quali Support. How are you?

Please make a 8.0.0/8.1.0/8.2.0/8.3.0 revision by stating:

1) Shellfoundary v1.2.0/v1.2.1 (and older releases, of course) doesn't work if there's a proxy server present between a Shellfoundry machine and a remote Quali Server machine.

This is a known limitation of Shellfoundary that's been confirmed by Quali Support and Shells team this week.

Please see our Quali Support ticket [#35384](https://qualisystemscom.zendesk.com/agent/tickets/35384) for full story if interested, and consult with our Shells team if needed.

Thank you.

**Comment by TomerAdmon** [comment]
Hi @jporori, 
Would you like this info to be added to the guide? or there is something I'm missing?

Tomer

**Comment by jporori** [comment]
Hi Tomer,

Yes, please add this information to our CloudShell 8.0 GA/8.1 GA/8.2 GA/8.3 GA guide.

It’ll help Shellfoundry users at Quali customer sites be aware of this, before getting started or checking back for any useful information.

Thank you.

Dennis Chen  |  Lead Customer Support Engineer, North America
Office: (408) 588-1774 Ext.539
Mobile: (408) 324-4566
Fax: (408) 986-8176

Quali Email: dennis.c@quali.com<mailto:dennis.c@quali.com>
Quali Website: www.quali.com<http://www.quali.com/>


[cid:image001.jpg@01D1D515.346663D0]
D e v O p s   A u t o m a t i o n
[cid:image002.jpg@01D1D515.346663D0]<https://twitter.com/qualisystems>[cid:image003.jpg@01D1D515.346663D0]<https://www.facebook.com/QualiSystems> [cid:image004.jpg@01D1D515.346663D0] <https://www.linkedin.com/company/qualisystems>  [cid:image005.jpg@01D1D515.346663D0] <http://www.youtube.com/user/QualiSystems>  [cid:image006.jpg@01D1D515.346663D0] <https://plus.google.com/+Qualisystems1/posts>

**Comment by TomerAdmon** [comment]
@Shnitselon  - Let's focus the discussion here on what is missing at the moment in the documentation.
For each limitation, we can open an internal bug and handle it internally without posting it publicly.

**Comment by Shnitselon** [comment]
updated the dev guide's Getting Started (with shells) and Shellfoundry articles.
@TomerAdmon @jporori
