### ISSUE TITLE
New suggestion for /shells/9.0.0/debugging-shell-commands.html

### ISSUE THREAD

**Issue by tim-spiglanin** [QualiSystems/devguide_source#187]
In the Gen 2 section, there's a missing import for CancellationContext:

if __name__ == "__main__":
    import mock
    from cloudshell.shell.core.driver_context import CancellationContext

**Comment by TomerAdmon** [comment]
Thanks @tim-spiglanin, 👍 
We will include the change in one of the next releases of the DevGuide.

**Comment by Shnitselon** [comment]
fixed
