### ISSUE TITLE
New suggestion for /shells/9.1.0/implementing-discovery-for-inventory-shells.html

### ISSUE THREAD

**Issue by sadanandhegde** [QualiSystems/devguide_source#202]
There are examples pointing to two different ways of importing context (or driver_context). Which is the correct way?
This is confusing, can you please make this consistent?

For example:
From this page 
`https://devguide.quali.com/shells/9.1.0/implementing-discovery-for-inventory-shells.html `
there is a link to 
`https://github.com/QualiSystems/devguide_examples/blob/master/2nd%20gen%20shells%20-%20implementing_discovery/src/driver.py`
Here it says:
`from cloudshell.shell.core.driver_context import InitCommandContext,`

and from this page
`https://devguide.quali.com/shells/9.1.0/driver-deep-dive.html`
there is a link to 
`https://github.com/QualiSystems/devguide_examples/blob/driver_deep_dive/adding_examples/driver_deep_dive/src/driver.py`
Here it says:

`from cloudshell.shell.core.context import InitCommandContext, `

**Comment by Shnitselon** [comment]
Hi Tomer,

Please advise.

**Comment by TomerAdmon** [comment]
@Costya-Y  - Can you assist? maybe it's related to cloudshell-shell-core versions?

**Comment by Costya-Y** [comment]
Hi,

Sure Tomer.

Steven, we'd removed `context` file almost a year ago from our `cloudshell-shell-core`.
So please change:
`cloudshell.shell.core.context import InitCommandContext`
to
`from cloudshell.shell.core.driver_context import InitCommandContext`

**Comment by Shnitselon** [comment]
@Costya-Y  - which CloudShell versions does this update apply to?

**Comment by Shnitselon** [comment]
updated https://github.com/QualiSystems/devguide_examples/blob/driver_deep_dive/adding_examples/driver_deep_dive/src/driver.py import line accordingly
