### ISSUE TITLE
New suggestion for /orchestration/9.0.0/getting-information-from-cloudshell.html

### ISSUE THREAD

**Issue by ayeleta** [QualiSystems/devguide_source#205]
Hi,
It can be helpful to specify the recommended requirements for  cloudshell-orch-core  (Or any other common package like cloudshell-automation-api) in the devguide according to CloudShell's version
Thanks

**Comment by TomerAdmon** [comment]
Thanks @ayeleta , 
We need to think about it as it's a relatively high maintenance list.
The best practice with orchestration will be to always copy the latest default orchestration script you have with your system and use it as a baseline, this will reassure that you are using the right cloudshell-orch-core version with your version.
Regarding cloudshell-atuomation-api - this package is versioned the same as CloudShell, so you can always use CloudShell X.Y and use with "cloudshell-automation-api >=X.Y.0.0,<X.Y+1.0.0

**Comment by ayeleta** [comment]
Hi,
Why is it high maintenance? You already  have a dev guide for each version, so you just need to specify the requirements there.
If not, I recommend putting the best practices you mentioned below as part of the dev guide, since customers that want to develop are not aware of that
Thanks

**Comment by TomerAdmon** [comment]
Thanks for the recommendation. We will consider to add it.

**Comment by TomerAdmon** [comment]
https://devguide.quali.com/orchestration/9.2.0/getting-started.html#best-practices-for-working-with-orchestration-scripts

**Comment by TomerAdmon** [comment]
Resolved #206
