### ISSUE TITLE
New suggestion for /reference/9.2.0/defining-Azure-custom-routing.html

### ISSUE THREAD

**Issue by qarbondev** [QualiSystems/devguide_source#225]
Regarding the suggestion:
"Add the script as a blueprint script to CloudShell and attach it to your blueprint. If this is a setup script, set the script’s Script Type to Setup to ensure that CloudShell will execute it automatically when a user reserves the blueprint"

You can only have one setup script attached to a blueprint and this will be the default for Azure that provisions and configures the resources. By overriding this script with another of type setup, you will potentially lose this functionality.

We have the option of interjecting python functions into the custom workflow that is covered elsewhere in the Dev Guide.

**Comment by Shnitselon** [comment]
added a note explaining this point - see below. will be uploaded shortly

![image](https://user-images.githubusercontent.com/20701198/63753351-92de6a00-c8bb-11e9-91e3-fcd400becd92.png)
