### ISSUE TITLE
New suggestion for /reference/9.2.0/defining-Azure-custom-routing.html

### ISSUE THREAD

**Issue by qarbondev** [QualiSystems/devguide_source#226]
Regarding the follow text:
"To do this, you need to use a blueprint or custom setup script that will tell the Azure cloud provider resource to define the custom routing (using the resource’s CreateRouteTable hidden command).

First, open the script and add the following code"

The supplied code is JSON text defining the routing rather than script code. It might be worth reviewing this article to ensure it is clear.

**Comment by Shnitselon** [comment]
fixed. explained in the article that the developer will need to create a JSON file for the custom routing code and make sure the script calls it
