### ISSUE TITLE
New suggestion for /reference/9.3.0

### ISSUE THREAD

**Issue by DYeag** [QualiSystems/devguide_source#237]
Hi,

This is a suggestion for a new page in the reference section of the devguide.

Just recently and also in the past, customers have told me about how confusing our python packages can be when trying to develop any custom scripts or deal with any requirements.txt issues. I believe it would be worth it to at least have a page that lists all of our python packages and a link to the pypi page of each so they can get more info on the packages if they wish. This page could be split into two section, one for the general and more utilized packages (cloudshell-automation-api, cloudshell-logging, cloudshell-core, etc). Another section could be for the more specific and less utilized packages (device specific networking packages for example).

Thanks,
Danny

**Comment by Shnitselon** [comment]
added a [Common CloudShell Packages](https://devguide.quali.com/reference/9.3.0/common-cloudshell-packages.html) reference article on 12/12/2019
