### ISSUE TITLE
New suggestion for /devops/9.3.0/available-apis.html

### ISSUE THREAD

**Issue by YonathanDruck** [QualiSystems/devguide_source#255]
Need to correct Script to use new connector command SetConnectorsInReservation

from cloudshell.api.cloudshell_api import SetConnectorRequest
from cloudshell.workflow.orchestration.sandbox import Sandbox

sandbox = Sandbox()
reservation_id = sandbox.reservationContextDetails.id

resource_list = ['PUT Mock', 'PUT Mock/Port 1', 'Traffic Mock', 'Traffic Mock/Port 1']

time.sleep(3)

sandbox.automation_api.AddResourcesToReservation(reservationId=reservation_id, resourcesFullPath=resource_list)
time.sleep(1)
print ""
sandbox.automation_api.WriteMessageToReservationOutput(reservation_id, "resources added to sandbox")

time.sleep(3)
sandbox.automation_api.SetResourceLiveStatus('PUT Mock', 'Online', "Active")
sandbox.automation_api.SetResourceLiveStatus('Traffic Mock', 'Online', "Active")

time.sleep(1)
sandbox.automation_api.WriteMessageToReservationOutput(reservation_id, "resources are online")

time.sleep(3)
connector_request = SetConnectorRequest('PUT Mock/Port 1', 'Traffic Mock/Port 1', 'bi', 'API-created route')
sandbox.automation_api.SetConnectorsInReservation(reservationId=reservation_id, connectors=[connector_request])
time.sleep(1)
sandbox.automation_api.WriteMessageToReservationOutput(reservation_id, "resources connected")

**Comment by Shnitselon** [comment]
Hi Yonathan,

Can you show me?

**Comment by Shnitselon** [comment]
@YonathanDruck , thank you so much for this feedback. Updated the devguide accordingly
