### ISSUE TITLE
New suggestion for /reference/9.3.0/common-cloudshell-packages.html

### ISSUE THREAD

**Issue by YonathanDruck** [QualiSystems/devguide_source#256]
cloudshell-logging fails on pip install

  Using cached cloudshell-logging-1.0.3.zip (19 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\tools\python2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\yonathan.d\\appdata\\local\\temp\\pip-install-uijvy9\\cloudshell-logging\\setup.py'"'"'; __file__='"'"'c:\\users\\yonathan.d\\appdata\\local\\temp\\pip-inst
all-uijvy9\\cloudshell-logging\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\yonathan.d\appdata\local\temp\p
ip-install-uijvy9\cloudshell-logging\pip-egg-info'
         cwd: c:\users\yonathan.d\appdata\local\temp\pip-install-uijvy9\cloudshell-logging\
    Complete output (1 lines):
    error in cloudshell-logging setup command: 'tests_require' must be a string or list of strings containing valid project/version requirement specifiers; Expected version spec in mock; python_version <= '2.7' at ; python_version <= '2.7'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Shnitselon** [comment]
@Costya-Y 
What do you think?

**Comment by Costya-Y** [comment]
Hi @Shnitselon and @YonathanDruck,

Thank you for the feedback!

Can you please do pip list and attach it here or you can create an issue in the [cloudshell-logging](https://github.com/QualiSystems/cloudshell-logging) repo

Cheers,
Costya

**Comment by YonathanDruck** [comment]
Hi,
After some testing it only fails pip install when using python 2.7.1.

**Comment by Costya-Y** [comment]
Hi,

Ok, please make sure you are using setuptools => 40.0
I believe that would fix the issue.

Thank you,
Costya

**Comment by Shnitselon** [comment]
Hi @Costya-Y , are we going to implement a fix for this or would you like it documented in the devguide/readmes?

**Comment by Costya-Y** [comment]
Hi @Shnitselon 

It's already been [fixed](https://github.com/QualiSystems/cloudshell-logging/blob/dev/setup.py#L12)
We can close this issue.
