### ISSUE TITLE
Provide Windows option in using compiling vendor SNMP example

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/devguide_source#31]
From @yaniv-k :
  "We suggest using smidump, a simple Linux package to compile MIBs
                                                               i.      It’s nice that we recommend, but not everyone are using linux/mac – if they’ll have to search on their own how to do it on windows, it will probably won’t get them the same kind of results that are expected by pysnmp.
                                                             ii.      Pysnmp 4.3.x is using pysmi to compile mibs, and this is something that can be used on windows (and maybe we don’t even need to convert the mibs to python)
1.       Starting from PySNMP 4.3.x, plain-text (ASN.1) MIBs can be automatically parsed into PySNMP form by the PySMI tool".

Can we extend the documentation to provide a Windows use case as well?

**Comment by LuizaNacshon** [comment]
Hi @yaniv-k. Thanks for your input.
I will update the documentation for Windows users ASAP.
Best,
Luiza

**Comment by doppleware** [comment]
Resolved with #50
