### ISSUE TITLE
Add more info about each shell template and when to use it

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/devguide_source#35]

**Comment by doppleware** [comment]
From Sadanand.S@quali.com: Would be good to have a high level description of what each of the template is, what/when/which is recommended to be used

**Comment by TomerAdmon** [comment]
@alonagetzler  - Hi, Can you please work with @Shnitselon and decide if this information is important to you and update accordingly?

**Comment by alonagetzler** [comment]
Hi,
The [section ](https://devguide.quali.com/shells/8.3.0/modeling-the-shell.html) that refers to the different standards and templates has been improved since this feedback was raised and in my opinion it is good enough at this stage.
I'm resolving this issue.
