### ISSUE TITLE
Add chapter about "external scripts" - running outside of the CloudShell context

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/devguide_source#39]
Add another chapter/page for creating scripts that runs outside of cloudshell, but wants to use the cloudshell api.

What to install (pip install cloudshell-automation-api)
Note about that it needs to be specific to the version they are running
(something like pip install "cloudshell-automation-api>=7.0.0.0,<7.1.0.0")

And then a simple example on how to connect to the server and run something:
And/or how to use the helpers, etc
import cloudshell.api.cloudshell_api

csapi = cloudshell.api.cloudshell_api.CloudShellAPISession("localhost", "admin", "admin", "Global")
csapi.GetCurrentReservations()

**Comment by doppleware** [comment]
@kalsky How are the helpers relevant? They only help you when you're running scripts **inside** cloudShell no?
It seem the use case is better handled by the REST API to create a reservation.
Executing commands will be the main use case, although in 7.2 that too will be a part of the REST API.
Are there additional use cases I'm missing?

**Comment by kalsky** [comment]
yes, helpers are not relevant in this case.
These scripts can be anything from user management to inventory management and other use cases that might be relevant for use with the rest api.
If you think some parts or some examples should use the rest api (do you mean the sandbox api?) then these samples/instruction should be added as well to the dev guide.
For the admin management you'll need to use the cloudshell api for now (and in 7.2).

**Comment by doppleware** [comment]
Added initial commit. Please open issues to additional enhancements you think are missing
