### ISSUE TITLE
reference to cloudshell-shell-core is wrong

### ISSUE THREAD

**Issue by ayeleta** [QualiSystems/devguide_source#56]
in https://qualisystems.github.io/devguide/shells/driver-deep-dive.html, you mention that what comes with the template requirements is "cloudshell-shell-core>=2.0.0,<2.1.0" - which is correct. 
But later, you use:
from cloudshell.shell.core.session.cloudshell_session import CloudShellSessionContext
which is not available in these versions of the core (and your example driver is actually using "cloudshell-shell-core>=2.1.0,<2.2.0").

Please update the text and/or the templates so that this would work.

Also, it is not clear when we can use a newer version of the shell-core. For the api, you mention how to take the version that is relevant to the cloudshell version - but what is the logic for the other packages? it is not mentioned anywhere on which versions of cloudshell they work (if relevant at all per package).

**Comment by doppleware** [comment]
currently the core packages are relevant regardless of a CloudShell release.
We'll occasionally update the template version and won't always go back to update all examples/existing docs which is okay.
If there is an example that doesn't work because the version is wrong there we'll look into it.

**Comment by ayeleta** [comment]
The example above doesn't work.
from cloudshell.shell.core.session.cloudshell_session import CloudShellSessionContext doesn't exist if using cloudshell-shell-core>=2.0.0,<2.1.0
