### ISSUE TITLE
add information about discovery special attributes

### ISSUE THREAD

**Issue by kalsky** [QualiSystems/devguide_source#60]
There are 4 special attribute names that you can use in the attributes list that you return in your driver.

These are mapped on the server to the resource properties:

ResourceName - will allow you to update the resource name (mostly relevant for updating the root resource name)

ResourceAddress - update the resource address (again, mostly relevant for the root resource)

ResourceDescription - update the resource description

ResourceUniqueIdentifier - update the unique id (this is less important with the python drivers since you have a specific input for that in the AutoLoadResource class).

**Comment by doppleware** [comment]
Fixed with b8bd882d787b3f086c558e8839523e98becc871f
