### ISSUE TITLE
Typo in quali_config.json structure

### ISSUE THREAD

**Issue by arueth** [QualiSystems/devguide_source#67]
On the Scripts Deep Dive page(https://qualisystems.github.io/devguide/orchestration/scripts-deep-dive.html) the two = in the quali_config.json should be :

The quali_config.json should have the following structure:

{
    "user" : "USER",
    "password" : "PASSWORD",
    "domain" : "DOMAIN",
    "server_address" : "SERVER_ADDRESS",
    "cloudshell_api_port" :"CLOUDSHELL_API_PORT",
    "reservation_id" **=** "reservation_id",
    "command_parameters" **=** { "PARAM_NAME" : "PARAM_VALUE"    }
}

should be:

{
    "user": "USER",
    "password": "PASSWORD",
    "domain": "DOMAIN",
    "server_address": "SERVER_ADDRESS",
    "cloudshell_api_port":"CLOUDSHELL_API_PORT",
    "reservation_id"**:** "reservation_id",
    "command_parameters"**:** { "PARAM_NAME" : "PARAM_VALUE"    }
}

**Comment by arueth** [comment]
This is fixed in Pull Request 61 (https://github.com/QualiSystems/devguide_source/pull/61)

**Comment by TomerAdmon** [comment]
fixed
